<?php
   add_filter( 'elementor/icons_manager/additional_tabs', 'qizon_custom_icons_filters' , 9999999, 1 );
   function qizon_custom_icons_filters( $tabs = array() ) {
      $newicons = [
         'qicon-camera',
         'qicon-video-camera-2',
         'qicon-camera-1',
         'qicon-shopping-cart',
         'qicon-shopping-cart-1',
         'qicon-creativity',
         'qicon-creativity-1',
         'qicon-invention',
         'qicon-smartphone',
         'qicon-smartphone-1',
         'qicon-nanotechnology',
         'qicon-nanotechnology-1',
         'qicon-browser',
         'qicon-web',
         'qicon-crowdfunding',
         'qicon-crowdfunding-1',
         'qicon-crowdfunding-2',
         'qicon-crowdfunding-3',
         'qicon-fundraise',
         'qicon-crowdfunding-4',
         'qicon-chat',
         'qicon-speech-bubble',
         'qicon-chat-1',
         'qicon-plus',
         'qicon-minus',
         'qicon-add',
         'qicon-search',
         'qicon-search-1',
         'qicon-call',
         'qicon-email-2',
         'qicon-location',
         'qicon-entrepreneur',
         'qicon-location-1',
         'qicon-contact',
         'qicon-pin-1',
         'qicon-share',
         'qicon-check',
         'qicon-checked',
         'qicon-stethoscope-1',
         'qicon-tshirt',
         'qicon-video-camera',
         'qicon-project-management',
         'qicon-salad',
         'qicon-reading-book',
         'qicon-crowdfunding-5',
         'qicon-earth-day',
         'qicon-save',
         'qicon-badge',
         'qicon-support',
         'qicon-debit-card',
         'qicon-payment',
         'qicon-wallet',
         'qicon-phone',
         'qicon-pin-2',
         'qicon-phone-call',
         'qicon-email-3',
         'qicon-account',
         'qicon-cyborg',
         'qicon-reading-book-1',
         'qicon-fashion',
         'qicon-medical-file',
         'qicon-design',
         'qicon-success',
         'qicon-budget',
         'qicon-human-resources',
         'qicon-mission-2',
         'qicon-mission-3',
         'qicon-relationship',
         'qicon-trusted',
         'qicon-cost-saving',
         'qicon-scrum',
         'qicon-recommend',
         'qicon-group',
         'qicon-campaign',
         'qicon-miscellaneous',
         'qicon-confirmation',
         'qicon-video-camera-1',
         'qicon-lamp',
         'qicon-mountain',
         'qicon-rocket',
         'qicon-money-bag',
         'qicon-crowdfunding-6',
         'qicon-invention-1',
         'qicon-email',
         'qicon-email-1',
         'qicon-pin',
         'qicon-networking',
         'qicon-photograph',
         'qicon-translation',
         'qicon-stethoscope',
         'qicon-skincare',
         'qicon-computer',
         'qicon-graphic-designer',
         'qicon-checkmark',
         'qicon-mission',
         'qicon-mission-1',
         'qicon-team',
         'qicon-team-1',
         'qicon-increment',
         'qicon-increment-1',
         'qicon-right-arrow',
         'qicon-left-arrow',
         'qicon-handshake',
         'qicon-thumbs-up',
         'qicon-thumbs-up-1'
      ];

      $icons['gva_custom_icon'] = array(
           'name'          => 'qizon-icons-theme',
           'label'         => esc_html__( 'Icons Theme', 'qizon-themer' ),
           'labelIcon'     => 'fas fa-user',
           'prefix'        => '',
           'displayPrefix' => '',
           'icons'         => $newicons,
           'url'          => GAVIAS_QIZON_PLUGIN_URL . 'assets/icons/style.css',
           'ver'           => '1.0',
       );

      return array_merge( $tabs, $icons );
   }

   add_action( 'wp_print_footer_scripts', 'qizon_insert_icons_footer_css'  );
   function qizon_insert_icons_footer_css() {
      echo '<link rel="stylesheet" type="text/css" href="' . GAVIAS_QIZON_PLUGIN_URL . 'assets/icons/style.css">';
   }
